scripts: Improve handling of errors from subsidiary scripts
This patch is to fix the handling of errors by 'lsdevinfo' from
invocations of 'ofpathname' that also encounter errors.  Error
messages from 'ofpathname' were being sent through 'stdout', and
interpreted as valid data by a number of script instructions in
'lsdevinfo'.  Following is an example of such a failure when the
error results were forwarded to an associated HMC.

    2019-02-19 22:05:38.212 [TID-5f68--72195] VIOS_CACHE: CacheVios.<-> saveCacheData 3*9080-M9S*130A068 cmd=lsdevinfo -c -q physloc=U78CD.001.FZH0128-P1-C1-T3-S4 -F status
    2019-02-19 22:05:38.212 [TID-5f68--72195] RMC_VIOS: PIRmcViosClient.stdErr=/bin/ls: cannot access /sys/class/net/ofpathname:: No such file or directory
    /bin/ls: cannot access Could: No such file or directory
    /bin/ls: cannot access not: No such file or directory
    /bin/ls: cannot access retrieve: No such file or directory
    /bin/ls: cannot access logical: No such file or directory
    /bin/ls: cannot access device: No such file or directory
    /bin/ls: cannot access name: No such file or directory
    /bin/ls: cannot access for: No such file or directory
    /bin/ls: cannot access Open: No such file or directory
    /bin/ls: cannot access Firmware: No such file or directory
    /bin/ls: cannot access path: No such file or directory
    /bin/ls: cannot access "/pci@800000029008004/ethernet@0"./device/driver: No such file or directory

This patch makes the following changes:

* Redirects the error messages from 'ofpathname' to stderr
* Adds more checks to 'lsdevinfo' to filter out stderr text
  from input to various parsing commands.

Signed-off-by: Michael Bringmann <mwb@linux.vnet.ibm.com>
Signed-off-by: Tyrel Datwyler <tyreld@linux.vnet.ibm.com>

diff --git a/scripts/ofpathname b/scripts/ofpathname
--- a/scripts/ofpathname
+++ b/scripts/ofpathname
@@ -84,20 +84,20 @@ err()
     fi
 
     case $emsg in
-        1)  echo "$OFPATHNAME: Could not retrieve Open Firmware device path"
-            echo "            for logical device \"$DEVNAME_ARG\"." ;;
+        1)  echo "$OFPATHNAME: Could not retrieve Open Firmware device path" 1>&2
+            echo "            for logical device \"$DEVNAME_ARG\"." 1>&2 ;;
 
-        2)  echo "$OFPATHNAME: sysfs (/sys) is needed and does not appear"
-            echo "            to be mounted on this system." ;;
+        2)  echo "$OFPATHNAME: sysfs (/sys) is needed and does not appear" 1>&2
+            echo "            to be mounted on this system." 1>&2 ;;
 
-        3)  echo "$OFPATHNAME: Could not find sysfs information for logical"
-            echo "            device \"$DEVNAME_ARG\"." ;;
+        3)  echo "$OFPATHNAME: Could not find sysfs information for logical" 1>&2
+            echo "            device \"$DEVNAME_ARG\"." 1>&2 ;;
 
-        4)  echo "$OFPATHANME: Logical device \"$DEVNAME_ARG\" does not appear"
-            echo "            to be configured." ;;
+        4)  echo "$OFPATHANME: Logical device \"$DEVNAME_ARG\" does not appear" 1>&2
+            echo "            to be configured." 1>&2 ;;
 
-        5)  echo "$OFPATHNAME: Could not retrieve logical device name for"
-            echo "            Open Firmware path \"$DEVNAME_ARG\"."
+        5)  echo "$OFPATHNAME: Could not retrieve logical device name for" 1>&2
+            echo "            Open Firmware path \"$DEVNAME_ARG\"." 1>&2 ;;
     esac
 
     exit 1
@@ -1631,7 +1631,7 @@ of2l_nvme()
 #
 . $PSERIES_PLATFORM
 if [[ $platform = $PLATFORM_POWERNV ]]; then
-	echo "$OFPATHNAME: is not supported on the $platform_name platform"
+	echo "$OFPATHNAME: is not supported on the $platform_name platform" 1>&2
 	exit 1
 fi
 
