update_flash: Stop kexec service before starting firmware update
We run 'reboot' call before initiating firmware update. If kexec service
is enabled, then we endup booting into new kernel instead of starting
firmware update.

This patch validates kexec service and if required stops this service
before starting code update.

Sample output:
  update_flash -v -f /home/hegdevasant/01SV840_032_032.img
  info: Current fixpack level is unknown.

  Projected Flash Update Results:
  Current T Image: UNKNOWN
  Current P Image: SV840_031
  New T Image:     SV840_032
  New P Image:     SV840_031

  info: kexec service is running. It will be stopped before flashing.

Signed-off-by: Vasant Hegde <hegdevasant@linux.vnet.ibm.com>

diff --git a/scripts/update_flash_nv b/scripts/update_flash_nv
--- a/scripts/update_flash_nv
+++ b/scripts/update_flash_nv
@@ -25,6 +25,7 @@ E_OPAL=8	# OPAL call failed
 E_USER=9	# User aborted operation
 E_OVERWRITE=10	# Auto overwrite permanent side image
 E_WRNTY=15	# Update Access Key Expired
+E_KEXEC=16	# Kexec service stop error
 
 # Firmware update related files
 SYS_IMAGE_FILE=/sys/firmware/opal/image
@@ -134,6 +135,35 @@ validate_sysfs_file() {
 	fi
 
 	error $E_SYS_FS "sysfs interface for firmware update does not exists."
+}
+
+# Check kexec service status
+check_kexec_service() {
+	# check systemctl command
+	which systemctl >/dev/null 2>&1
+	if [ $? -ne 0 ]; then
+		return 1
+	fi
+
+	# kexec service is running
+	systemctl status kexec.service | grep -w "active" >/dev/null 2>&1
+	if [ $? -eq 0 ]; then
+		return 0
+	fi
+
+	return 1
+}
+
+# Stop kexec service
+stop_kexec_service() {
+	systemctl stop kexec.service >/dev/null 2>&1
+	if [ $? -ne 0 ]; then
+		echo "update_flash: Failed to stop kexec service."
+		error $E_KEXEC "Please stop kexec service and retry."
+	fi
+
+	echo
+	echo "info: kexec service stopped."
 }
 
 # Copy image to sysfs file
@@ -277,6 +307,13 @@ validate_flash_from_file() {
 	# Validate candidate image
 	validate_flash
 
+	# Check kexec service status
+	check_kexec_service
+	if [ $? -eq 0 ]; then
+		echo
+		echo "info: kexec service is running. It will be stopped before flashing."
+	fi
+
 	exit $E_SUCCESS
 }
 
@@ -316,6 +353,12 @@ update_flash_from_file() {
 	echo 1 > $SYS_UPDATE_FLASH 2>/dev/null
 	output="$(cat $SYS_UPDATE_FLASH)"
 	echo_update_return_status "$output"
+
+	# Stop kexec service
+	check_kexec_service
+	if [ $? -eq 0 ]; then
+		stop_kexec_service
+	fi
 
 	# Reboot system, so that we can flash new image
 	reboot
