update_flash_nv: improve check_ipmitool
This patch adds a quick test in check_ipmitool to make sure the
BMC is alive

Signed-off-by: Cédric Le Goater <clg@fr.ibm.com>

diff --git a/scripts/update_flash_nv b/scripts/update_flash_nv
--- a/scripts/update_flash_nv
+++ b/scripts/update_flash_nv
@@ -453,6 +453,13 @@ check_ipmitool() {
 		echo "update_flash: ipmitool command not found."
 		error $E_IPMI "Please install ipmitool and retry."
 	fi
+
+	# Is BMC alive ?
+	ipmitool -I usb mc info >/dev/null 2>&1 && break;
+	if [ $? -ne 0 ]; then
+		echo "update_flash: Failed to connect to BMC."
+		error $E_IPMI "Please try again."
+	fi
 }
 
 opp_query_flash_support() {
